version: '3.1'

services:

  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - NODE_ENV=production
      - WEBHOOK_URL=https://${DOMAIN_NAME}
    ports:
      - 5678:5678
    volumes:
      - /data/n8n:/home/node/.n8n
